In [24]:



import numpy as np
# X = (hours sleeping, hours studying), y = test score of the student
X = np.array([[2, 9], [1, 5], [3, 6]])
y = np.array([[92], [86], [89]])

# scale units
X = X/np.amax(X, axis=0) #maximum of X array
y = y/100 # maximum test score is 100
np.random.seed(2)
class NeuralNetwork():
    def __init__(self,inp_size,output_size,hidden_size):
        self.inp_size=inp_size
        self.output_size=output_size
        self.hidden_size=hidden_size
        self.bias1=0
        self.bias2=0
        
        self.W1=np.random.uniform(-0.5,0.5,(self.inp_size,self.hidden_size))
        self.W2=np.random.uniform(-0.5,0.5,(self.hidden_size,self.output_size))
    
    def feedforward(self,X):
        
        self.input_sum=np.dot(X,self.W1)+self.bias1
        self.hid_inp=self.sigmoid(self.input_sum)
        
        self.hid_sum=np.dot(self.hid_inp,self.W2)+self.bias2
        output=self.sigmoid(self.hid_sum)
        return output
    
    
    def backpropagation(self, X, y, output, lr):
        self.error = y - output
        self.output_delta = self.error * self.sigmoid_derivative(output)
        
        self.hidden_error = self.output_delta.dot(self.W2.T) 
        self.hidden_delta = self.hidden_error * self.sigmoid_derivative(self.hid_inp)

        self.W1 += X.T.dot(self.hidden_delta) * lr
        self.W2 += self.hid_inp.T.dot(self.output_delta) * lr

        self.bias1 += np.sum(self.hidden_delta) * lr
        self.bias2 += np.sum(self.output_delta) * lr

        
    def sigmoid(self,x):
        return 1/(1+np.exp(-x))
    
    def sigmoid_derivative(self,s):
        return s*(1-s)
    def train(self,X,y,epochs):
        for i in range(epochs):
            output=self.feedforward(X)
            self.backpropagation(X,y,output,0.1)
            if i%1000 == 0:
                print(f"Epochs {i} Loss {np.mean(np.abs(y - output))}")
        
        
# NN=NeuralNetwork()

# for i in range(1000):
#     if i%500==0:
#         print('Loss=',np.mean(np.square(y-NN.feedforward(X))))
#     NN.train(X,y)
    
# print('Result=\n',NN.feedforward(X))
# print('Actual:\n',y)
# print('Loss=',np.mean(np.square(y-NN.feedforward(X))))

In [25]:
import pandas as pd
df=pd.read_csv('Iris.csv')

In [26]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [27]:
df['Species']=df['Species'].replace({'Iris-setosa':0, 'Iris-versicolor':1, 'Iris-virginica':2})

In [28]:
arr1=np.array([df['SepalLengthCm'],df['SepalWidthCm'],df['PetalLengthCm'],df['PetalWidthCm']]).T
arr2=np.array([df['Species']]).T
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
oe=OneHotEncoder()

In [29]:
xtrain,xtest,ytrain,ytest=train_test_split(arr1,arr2,test_size=0.2)

In [30]:
ytrain=oe.fit_transform(ytrain.reshape(-1,1)).toarray()

In [31]:
xtrain.shape,ytrain.shape

((120, 4), (120, 3))

In [53]:
inpsize=xtrain.shape[1]
outputsize=ytrain.shape[1]
hiddensize=50
lr=0.1
epochs=100000

In [54]:
nnet=NeuralNetwork(inpsize,outputsize,hiddensize)

In [55]:
nnet.train(xtrain,ytrain,epochs)

Epochs 0 Loss 0.5769758392656431
Epochs 1000 Loss 0.2356152330308069
Epochs 2000 Loss 0.029536199957720655
Epochs 3000 Loss 0.02205081390771129
Epochs 4000 Loss 0.020598757272238657
Epochs 5000 Loss 0.018579193049283307
Epochs 6000 Loss 0.019737139788934214
Epochs 7000 Loss 0.010772593189977652
Epochs 8000 Loss 0.009471694654085705
Epochs 9000 Loss 0.008879454144437828
Epochs 10000 Loss 0.008512889957763586
Epochs 11000 Loss 0.008276721420891336
Epochs 12000 Loss 0.008148110298020591
Epochs 13000 Loss 0.008176962600226656
Epochs 14000 Loss 0.008745664522693295
Epochs 15000 Loss 0.010743925199450506
Epochs 16000 Loss 0.012277240714185258
Epochs 17000 Loss 0.012742893972579158
Epochs 18000 Loss 0.01285330870957071
Epochs 19000 Loss 0.012809160394166094
Epochs 20000 Loss 0.01278420577604597
Epochs 21000 Loss 0.012824631545158935
Epochs 22000 Loss 0.011670689558864253
Epochs 23000 Loss 0.01093192560265399
Epochs 24000 Loss 0.013138552097142897
Epochs 25000 Loss 0.016332644634439324
Epochs 

In [56]:
print("SL|SW|PL|PW \t\t Predicted Class \t\t Actual Class")
for i in range(len(xtest)):
    predict = nnet.feedforward(xtest[i])
    predicted_class = np.argmax(predict)
    actual = ytest[i]
    print(f"{xtest[i]}\t\t{predicted_class}\t\t{actual}")

SL|SW|PL|PW 		 Predicted Class 		 Actual Class
[4.6 3.4 1.4 0.3]		0		[0]
[4.6 3.1 1.5 0.2]		0		[0]
[5.7 2.5 5.  2. ]		2		[2]
[4.8 3.  1.4 0.1]		0		[0]
[4.8 3.4 1.9 0.2]		0		[0]
[7.2 3.  5.8 1.6]		2		[2]
[5.  3.  1.6 0.2]		0		[0]
[6.7 2.5 5.8 1.8]		2		[2]
[6.4 2.8 5.6 2.1]		2		[2]
[4.8 3.  1.4 0.3]		0		[0]
[5.3 3.7 1.5 0.2]		0		[0]
[4.4 3.2 1.3 0.2]		0		[0]
[5.  3.2 1.2 0.2]		0		[0]
[5.4 3.9 1.7 0.4]		0		[0]
[6.  3.4 4.5 1.6]		1		[1]
[6.5 2.8 4.6 1.5]		1		[1]
[4.5 2.3 1.3 0.3]		0		[0]
[5.7 2.9 4.2 1.3]		1		[1]
[6.7 3.3 5.7 2.5]		2		[2]
[5.5 2.5 4.  1.3]		1		[1]
[6.7 3.  5.  1.7]		2		[1]
[6.4 2.9 4.3 1.3]		1		[1]
[6.4 3.2 5.3 2.3]		2		[2]
[5.6 2.7 4.2 1.3]		1		[1]
[6.3 2.3 4.4 1.3]		1		[1]
[4.7 3.2 1.6 0.2]		0		[0]
[4.7 3.2 1.3 0.2]		0		[0]
[6.1 3.  4.9 1.8]		2		[2]
[5.1 3.8 1.9 0.4]		0		[0]
[7.2 3.2 6.  1.8]		2		[2]


In [57]:
count = 0
total = len(xtest)
for i in range(total):
    
    predict = nnet.feedforward(xtest[i])
    predicted_class = np.argmax(predict)
    actual = ytest[i]
    if predicted_class == actual:
        count+=1
accuracy = (count/total)*100
print(f"{accuracy:.2f}%")

96.67%


In [58]:
ypred=nnet.feedforward(xtest)
ypred_classes=[np.argmax(element) for element in ypred]
ypred_classes
from sklearn.metrics import accuracy_score
acc=accuracy_score(ytest,ypred_classes)
acc*100

96.66666666666667

In [14]:
import numpy as np
# X = (hours sleeping, hours studying), y = test score of the student
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

# scale units
# X = X/np.amax(X, axis=0) #maximum of X array
# y = y/100 # maximum test score is 100
# X=np.array([[0,0,1,1,0,0,0,0],
#                [0,0,1,1,0,0,0,1],
#                [0,0,1,1,0,0,1,0],
#                [0,0,1,1,0,0,1,1],
#                [0,0,1,1,0,1,0,0],
#                [0,0,1,1,0,1,0,1],
#                [0,0,1,1,0,1,1,0],
#                [0,0,1,1,0,1,1,1],
#                [0,0,1,1,1,0,0,0],
#                [0,0,1,1,1,0,0,1]])

# y=np.array([[0],[1],[0],[1],[0],[1],[0],[1],[0],[1]])
class NeuralNetwork(object):
    def __init__(self):
        #parameters
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 15
        self.bias1=0
        self.bias2=0
        #weights
        self.W1 = np.random.randn(self.inputSize, self.hiddenSize) # (3x2) weight matrix from input to hidden layer
        self.W2 = np.random.randn(self.hiddenSize, self.outputSize) # (3x1) weight matrix from hidden to output layer
        
    def feedForward(self, X):
        #forward propogation through the network
        self.z = np.dot(X, self.W1)+self.bias1 #dot product of X (input) and first set of weights (3x2)
        self.z2 = self.sigmoid(self.z) #activation function
        self.z3 = np.dot(self.z2, self.W2)+self.bias2 #dot product of hidden layer (z2) and second set of weights (3x1)
        output = self.sigmoid(self.z3)
        return output
        
    def sigmoid(self, s, deriv=False):
        if (deriv == True):
            return s * (1 - s)
        return 1/(1 + np.exp(-s))
    
    def backward(self, X, y, output,lr):
        #backward propogate through the network
        self.output_error = y - output # error in output
        self.output_delta = self.output_error * self.sigmoid(output, deriv=True)
        
        self.z2_error = self.output_delta.dot(self.W2.T) #z2 error: how much our hidden layer weights contribute to output error
        self.z2_delta = self.z2_error * self.sigmoid(self.z2, deriv=True) #applying derivative of sigmoid to z2 error
        
        self.W1 += X.T.dot(self.z2_delta) # adjusting first set (input -> hidden) weights
        self.W2 += self.z2.T.dot(self.output_delta) # adjusting second set (hidden -> output) weights
        
        self.bias1+=np.sum(self.z2_delta)*lr
        self.bias2+=np.sum(self.output_delta)*lr
        
        
    def train(self, X, y):
        output = self.feedForward(X)
        self.backward(X, y, output,0.1)
        
NN = NeuralNetwork()

for i in range(10000): #trains the NN 1000 times
    if (i % 100 == 0):
        print("Loss: " + str(np.mean(np.square(y - NN.feedForward(X)))))
        pass
    NN.train(X, y)
        
print("Input: " , (X))
print("Actual Output: " , (y))
print("Loss: " , (np.mean(np.square(y - NN.feedForward(X)))))
print("\n")
print("Predicted Output: " ,(NN.feedForward(X)))

ypred=NN.feedForward(X)

predict=NN.feedForward(X[0])

Loss: 0.2766801422847673
Loss: 0.11103768300876314
Loss: 0.036414081298737265
Loss: 0.01697178819142473
Loss: 0.01023176478619698
Loss: 0.007094993054699653
Loss: 0.0053450908317975495
Loss: 0.00424888709142822
Loss: 0.003505623173197557
Loss: 0.002972087015387712
Loss: 0.0025723251057786513
Loss: 0.002262651416714106
Loss: 0.0020163027592903834
Loss: 0.0018160357284023989
Loss: 0.0016502737257416337
Loss: 0.0015109741313561248
Loss: 0.0013923857822582867
Loss: 0.0012902932959198952
Loss: 0.0012015402937883867
Loss: 0.001123718900806483
Loss: 0.00105496186353036
Loss: 0.0009937999456352848
Loss: 0.0009390619710587561
Loss: 0.0008898033993412393
Loss: 0.0008452543993708167
Loss: 0.0008047815051525032
Loss: 0.000767858897473425
Loss: 0.000734046615774795
Loss: 0.0007029738316003046
Loss: 0.0006743258678074592
Loss: 0.0006478340235499332
Loss: 0.0006232675245439418
Loss: 0.0006004270999121642
Loss: 0.0005791398159380828
Loss: 0.0005592548898014059
Loss: 0.00054064027378307
Loss: 0.0005231

In [51]:
print(1) if predict<0.5 else print(0)

1


In [26]:
import numpy as np

class NeuralNetwork:
    def __init__(self):
        self.input_size = 4
        self.output_size = 3
        self.hidden1_size = 50
        self.hidden2_size = 50
        self.bias1 = np.random.randn(1,(self.hidden1_size))
        self.bias2 = np.random.randn(1,(self.hidden2_size))
        self.bias3 = np.random.randn(1,(self.output_size))
        
        self.W1 = np.random.randn(self.input_size, self.hidden1_size)
        self.W2 = np.random.randn(self.hidden1_size, self.hidden2_size)
        self.W3 = np.random.randn(self.hidden2_size, self.output_size)
    
    def feedForward(self, X):
        self.input_sum1 = np.dot(X, self.W1) + self.bias1
        self.hid_inp1 = self.sigmoid(self.input_sum1)
        
        self.input_sum2 = np.dot(self.hid_inp1, self.W2) + self.bias2
        self.hid_inp2 = self.sigmoid(self.input_sum2)
        
        self.input_sum3 = np.dot(self.hid_inp2, self.W3) + self.bias3
        output = self.sigmoid(self.input_sum3)
        
        return output
    
    def backpropagation(self, X, y, output, lr):
        self.error = y - output
        self.output_delta = self.error * self.sigmoid_derivative(output)
        
        self.hidden2_error = self.output_delta.dot(self.W3.T)
        self.hidden2_delta = self.hidden2_error * self.sigmoid_derivative(self.hid_inp2)
        
        self.hidden1_error = self.hidden2_delta.dot(self.W2.T)
        self.hidden1_delta = self.hidden1_error * self.sigmoid_derivative(self.hid_inp1)

        self.W1 += X.T.dot(self.hidden1_delta) * lr
        self.W2 += self.hid_inp1.T.dot(self.hidden2_delta) * lr
        self.W3 += self.hid_inp2.T.dot(self.output_delta) * lr

        self.bias1 += np.sum(self.hidden1_delta) * lr
        self.bias2 += np.sum(self.hidden2_delta) * lr
        self.bias3 += np.sum(self.output_delta) * lr

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def sigmoid_derivative(self, s):
        return s * (1 - s)
    
    def train(self, X, y):
        output = self.feedForward(X)
        self.backpropagation(X, y, output, 0.1)
        



In [27]:
import pandas as pd

df=pd.read_csv('Iris.csv')

df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [28]:
from sklearn.preprocessing import LabelEncoder
LE=LabelEncoder()

In [29]:
df['Species']=LE.fit_transform(df['Species'])
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [30]:
from sklearn.preprocessing import OneHotEncoder
oe=OneHotEncoder()
x=np.array([df['SepalLengthCm'],df['SepalWidthCm'],df['PetalLengthCm'],df['PetalWidthCm']]).T
y=np.array([df['Species']]).T
y

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [31]:
y_train_hot = oe.fit_transform(y.reshape(-1, 1)).toarray()
y_train_hot.shape

(150, 3)

In [32]:



NN=NeuralNetwork()
for i in range(10000):
    NN.train(x,y)

In [33]:
# print("Input: " , (x))
# print("Actual Output: " , (y))
print("Loss: " , (np.mean(np.square(y - NN.feedForward(x)))))
print("\n")
print("Predicted Output: " ,(NN.feedForward(x)))

ypred=NN.feedForward(x)

# predict=NN.feedForward(X[0])

Loss:  0.6666666662626493


Predicted Output:  [[1.         1.         1.        ]
 [1.         1.         1.        ]
 [1.         1.         1.        ]
 [1.         1.         1.        ]
 [1.         1.         1.        ]
 [1.         1.         1.        ]
 [1.         1.         1.        ]
 [1.         1.         1.        ]
 [1.         1.         1.        ]
 [1.         1.         1.        ]
 [1.         1.         1.        ]
 [1.         1.         1.        ]
 [1.         1.         1.        ]
 [1.         1.         1.        ]
 [1.         1.         1.        ]
 [1.         1.         1.        ]
 [1.         1.         1.        ]
 [1.         1.         1.        ]
 [1.         1.         1.        ]
 [1.         1.         1.        ]
 [1.         1.         1.        ]
 [1.         1.         1.        ]
 [1.         0.99999999 1.        ]
 [1.         1.         1.        ]
 [1.         1.         1.        ]
 [1.         1.         1.        ]
 [1.         1.  

In [10]:
import numpy as np

# X = (hours sleeping, hours studying), y = test score of the student
X = np.array(([2, 9], [1, 5], [3, 6]))
y = np.array(([1, 0, 0], [0, 1, 0], [0, 0, 1]))  # One-hot encoding for multiclass classification

# scale units
X = X / np.amax(X, axis=0)  # maximum of X array
# No need to scale y since it's already one-hot encoded

np.random.seed(2)


class NeuralNetwork:
    def __init__(self):
        self.inp_size = 2
        self.output_size = 3  # Number of classes
        self.hidden1_size = 3
        self.hidden2_size = 5
        self.bias1 = 0
        self.bias2 = 0
        self.bias3 = 0

        self.W1 = np.random.randn(self.inp_size, self.hidden1_size)
        self.W2 = np.random.randn(self.hidden1_size, self.hidden2_size)
        self.W3 = np.random.randn(self.hidden2_size, self.output_size)

    def relu(self, x):
        return np.maximum(0, x)

    def softmax(self, x):
        exp_values = np.exp(x)
        return exp_values / np.sum(exp_values,axis=1,keepdims=True)

    def feedforward(self, X):
        self.input_sum1 = np.dot(X, self.W1) + self.bias1
        self.hid1_inp = self.relu(self.input_sum1)

        self.input_sum2 = np.dot(self.hid1_inp, self.W2) + self.bias2
        self.hid2_inp = self.relu(self.input_sum2)

        self.input_sum3 = np.dot(self.hid2_inp, self.W3) + self.bias3
        output = self.softmax(self.input_sum3)
        return output

    def relu_derivative(self, x):
        return np.where(x > 0, 1, 0)

    def backpropagation(self, X, y, output, lr):
        self.error = y - output
        self.output_delta = self.error  # No need to multiply by derivative of softmax as it's included in the derivative of cross-entropy loss

        self.hidden2_error = self.output_delta.dot(self.W3.T)
        self.hidden2_delta = self.hidden2_error * self.relu_derivative(self.hid2_inp)

        self.hidden1_error = self.hidden2_delta.dot(self.W2.T)
        self.hidden1_delta = self.hidden1_error * self.relu_derivative(self.hid1_inp)

        self.W1 += X.T.dot(self.hidden1_delta) * lr
        self.W2 += self.hid1_inp.T.dot(self.hidden2_delta) * lr
        self.W3 += self.hid2_inp.T.dot(self.output_delta) * lr

        self.bias1 += np.sum(self.hidden1_delta) * lr
        self.bias2 += np.sum(self.hidden2_delta) * lr
        self.bias3 += np.sum(self.output_delta) * lr

    def train(self, X, y):
        output = self.feedforward(X)
        self.backpropagation(X, y, output, 0.01)


NN = NeuralNetwork()

for i in range(10000):
    if i % 500 == 0:
        print('Loss=', -np.mean(y * np.log(NN.feedforward(X))))
    NN.train(X, y)

print('Result=\n', NN.feedforward(X))
print('Actual:\n', y)
print('Loss=', -np.mean(y * np.log(NN.feedforward(X))))


Loss= 0.38388625491969613
Loss= 0.2764609440588489
Loss= 0.25585836682037866
Loss= 0.2449608670268129
Loss= 0.24028192369941082
Loss= 0.23594449501646253
Loss= 0.2325842770257183
Loss= 0.2299573366982345
Loss= 0.22760564767535169
Loss= 0.22584719508980233
Loss= 0.2251643520994801
Loss= 0.22311823043262347
Loss= 0.22197307831975033
Loss= 0.22105995182398658
Loss= 0.22036815016207612
Loss= 0.2205828484860132
Loss= 0.24476910341962915
Loss= 0.21870440718227047
Loss= 0.24445454797795252
Loss= 0.2181475021490068
Result=
 [[9.93936926e-01 6.06307406e-03 1.49312829e-19]
 [3.33333333e-01 3.33333333e-01 3.33333333e-01]
 [3.33333333e-01 3.33333333e-01 3.33333333e-01]]
Actual:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
Loss= 0.24481178960710448
