In [112]:
import numpy as np
# Define the 4 vectors to be stored
vectors = np.array([[1, 1, -1, -1],
                [-1, -1, 1, 1],
                [1, -1, 1, -1],
                [-1, 1, -1, 1]])


In [113]:
# Calculate the weight matrix
# weights = np.zeros((4, 4))
# for i in range(4):
#     for j in range(4):
#         if i == j:
#             weights[i, j] = 0
#         else:
#             weights[i, j] = np.sum(vectors[i] * vectors[j])
import numpy as np
# Define the 4 vectors to be stored
vectors = np.array([[1, 1, -1, -1],
                [-1, -1, 1, 1],
                [1, -1, 1, -1],
                [-1, 1, -1, 1]])
def train(patterns):
    weights = np.zeros((4, 4))
    for pattern in patterns:
        pattern = np.array(pattern)
        outer_product = np.outer(pattern, pattern)  # Compute outer product
        print("Outer Product for Pattern:", pattern)
        print(outer_product)
        weights += outer_product
    np.fill_diagonal(weights, 0) 
    return weights
weights=train(vectors)

# Define the Hopfield network function
def hopfield(input_vector, weights):
#     output_vector = activation(np.dot(weights, input_vector))
#     return output_vector

    max_iterations=1
    iteration=0
    noisy_pattern = input_vector
    while(iteration<max_iterations):
        iteration+=1
        prev_pattern = np.copy(noisy_pattern)
        noisy_pattern = activation(np.dot(noisy_pattern, weights))
        if np.array_equal(noisy_pattern, prev_pattern):
            return noisy_pattern
            break
    return noisy_pattern

# Test the Hopfield network with one of the stored vectors as input
noisy_patterns = np.array([[1,-1, 1,-1]])
input_vector = noisy_patterns
output_vector = hopfield(input_vector, weights)
print("Input vector:")
print(input_vector)
print("Output vector:")
print(output_vector)

Outer Product for Pattern: [ 1  1 -1 -1]
[[ 1  1 -1 -1]
 [ 1  1 -1 -1]
 [-1 -1  1  1]
 [-1 -1  1  1]]
Outer Product for Pattern: [-1 -1  1  1]
[[ 1  1 -1 -1]
 [ 1  1 -1 -1]
 [-1 -1  1  1]
 [-1 -1  1  1]]
Outer Product for Pattern: [ 1 -1  1 -1]
[[ 1 -1  1 -1]
 [-1  1 -1  1]
 [ 1 -1  1 -1]
 [-1  1 -1  1]]
Outer Product for Pattern: [-1  1 -1  1]
[[ 1 -1  1 -1]
 [-1  1 -1  1]
 [ 1 -1  1 -1]
 [-1  1 -1  1]]


In [114]:
weights

array([[ 0.,  0.,  0., -4.],
       [ 0.,  0., -4.,  0.],
       [ 0., -4.,  0.,  0.],
       [-4.,  0.,  0.,  0.]])

In [115]:

# Define the activation function (in this case, a sign function)
def activation(x):
    return np.where(x > 0, 1, -1)


In [116]:
# Define the Hopfield network function
def hopfield(input_vector, weights):
#     output_vector = activation(np.dot(weights, input_vector))
#     return output_vector

    max_iterations=1
    iteration=0
    noisy_pattern = input_vector
    while(iteration<max_iterations):
        iteration+=1
        prev_pattern = np.copy(noisy_pattern)
        noisy_pattern = activation(np.dot(noisy_pattern, weights))
        if np.array_equal(noisy_pattern, prev_pattern):
            return noisy_pattern
            break
    return noisy_pattern



In [119]:
# Test the Hopfield network with one of the stored vectors as input
noisy_patterns = np.array([[1,-1, 1,-1]])
input_vector = noisy_patterns
output_vector = hopfield(input_vector, weights)
print("Input vector:")
print(input_vector)
print("Output vector:")
print(output_vector)

Input vector:
[[ 1 -1  1 -1]]
Output vector:
[[ 1 -1  1 -1]]


In [68]:
max_iterations=10

noisy_patterns = np.array([[1, -1,- 1, -1]])
for i, noisy_pattern in enumerate(noisy_patterns):
    iteration = 0
    while iteration < max_iterations:
        iteration += 1
        prev_pattern = np.copy(noisy_pattern)
        noisy_pattern = activation(np.dot(noisy_pattern, weights))
        if np.array_equal(noisy_pattern, vectors):
            break
            
#         distances = np.sum(np.abs(vectors - noisy_pattern), axis=1)
#         closest_match_idx = np.argmin(distances)
    
    # print the original pattern, noisy pattern, and recovered pattern
    print('{:<20} {:<10} {:<10}'.format("Original pattern", i, str(tuple(vectors[i]))))
    print('{:<20} {:<10} {:<10}'.format("Noisy pattern", i, str(tuple(noisy_patterns[i]))))
    print('{:<20} {:<10} {:<10}'.format("Recovered pattern", i, str(tuple(noisy_pattern))))
    
    print("")
    

Original pattern     0          (1, 1, 1, -1)
Noisy pattern        0          (1, -1, -1, -1)
Recovered pattern    0          (1, -1, -1, -1)



In [96]:
vectors

[array([ 1,  1, -1, -1]),
 array([-1,  1,  1, -1]),
 array([-1, -1,  1,  1]),
 array([ 1, -1, -1,  1])]

In [3]:
import numpy as np

def train_hopfield(patterns):
    num_neurons = patterns.shape[1]
    weights = np.zeros((num_neurons, num_neurons))
    for pattern in patterns:
        weights += np.outer(pattern, pattern)
    np.fill_diagonal(weights, 0)
    return weights

def update_neuron(weights, neuron_idx, state):
    activation = np.dot(weights[neuron_idx], state)
    return np.sign(activation)

def update_hopfield(weights, initial_state, max_iterations=100):
    current_state = initial_state.copy()
    for _ in range(max_iterations):
        neuron_idx = np.random.randint(len(initial_state))
        new_state = update_neuron(weights, neuron_idx, current_state)
        if np.array_equal(new_state, current_state):
            return new_state
        current_state[neuron_idx] = new_state
    return current_state

patterns = np.array([[1, 1, 1, -1],
                     [-1, 1, -1, 1],
                     [-1, 1, 1, -1],
                     [-1, -1, -1, 1]])

initial_state = np.array([-1, 1,- 1, 1])

weights = train_hopfield(patterns)
final_state = update_hopfield(weights, initial_state)

print("Initial State:", initial_state)
print("Final State:", final_state)

Initial State: [-1  1 -1  1]
Final State: [-1 -1 -1  1]


In [1]:
import numpy as np
# Define the 4 vectors to be stored
vectors = np.array([[1, 1, -1, -1],
                    [-1, -1, 1, 1],
                    [1, -1, 1, -1],
                    [-1, 1, -1, 1]])

# Calculate the weight matrix
weights = np.zeros((4, 4))
for i in range(4):
    for j in range(4):
        if i == j:
            weights[i, j] = 0
        else:
            weights[i, j] = np.sum(vectors[i] * vectors[j])
            
# Define the activation function (in this case, a sign function)
def activation(x):
    return np.where(x >= 0, 1, -1)

# Define the Hopfield network function
def hopfield(input_vector, weights):
    output_vector = activation(np.dot(weights, input_vector))
    return output_vector

# Test the Hopfield network with one of the stored vectors as input
input_vector = vectors[0]
output_vector = hopfield(input_vector, weights)
print("Input vector:")
print(input_vector)
print("Output vector:")
print(output_vector)

Input vector:
[ 1  1 -1 -1]
Output vector:
[-1 -1  1  1]


In [74]:
import numpy as np

class HopfieldNetwork:
    def __init__(self, n):
        self.n = n
        self.weights = np.zeros((n, n))

    def train(self, patterns):
        for pattern in patterns:
            pattern = np.array(pattern)
            self.weights += np.outer(pattern, pattern)
        np.fill_diagonal(self.weights, 0)
        
    def energy(self, state):
        return -0.5 * np.dot(np.dot(state, self.weights), state)

    def update(self, state, max_iter=100):
        for _ in range(max_iter):
            new_state = np.sign(np.dot(self.weights, state))
            if np.array_equal(new_state, state):
                return new_state
            state = new_state
        return state

# Test the network
if __name__ == "__main__":
    patterns = [[1, 1, -1, -1],
                [-1, -1, 1, 1],
                [1, -1, 1, -1],
                [-1, 1, -1, 1]]

    hopfield_net = HopfieldNetwork(4)
    hopfield_net.train(patterns)
    print(hopfield_net.weights)
    # Test recalling patterns
    for pattern in patterns:
        initial_state = np.array(pattern)
        recalled_state = hopfield_net.update(initial_state)
        print("Initial Pattern:", initial_state)
        print("Recalled Pattern:", recalled_state)
        print("Energy:", hopfield_net.energy(recalled_state))
        print()
    print(hopfield_net.weights)

[[ 0.  0.  0. -4.]
 [ 0.  0. -4.  0.]
 [ 0. -4.  0.  0.]
 [-4.  0.  0.  0.]]
Initial Pattern: [ 1  1 -1 -1]
Recalled Pattern: [ 1.  1. -1. -1.]
Energy: -8.0

Initial Pattern: [-1 -1  1  1]
Recalled Pattern: [-1. -1.  1.  1.]
Energy: -8.0

Initial Pattern: [ 1 -1  1 -1]
Recalled Pattern: [ 1. -1.  1. -1.]
Energy: -8.0

Initial Pattern: [-1  1 -1  1]
Recalled Pattern: [-1.  1. -1.  1.]
Energy: -8.0

[[ 0.  0.  0. -4.]
 [ 0.  0. -4.  0.]
 [ 0. -4.  0.  0.]
 [-4.  0.  0.  0.]]


In [95]:
import numpy as np

def train_hopfield_network(patterns):
    n = len(patterns[0])
    weights = np.zeros((n, n))

    for pattern in patterns:
        pattern = np.array(pattern)
        outer_product = np.outer(pattern, pattern)
        weights += outer_product

    np.fill_diagonal(weights, 0)
    return weights

def energy(state, weights):
    return -0.5 * np.dot(np.dot(state, weights), state)

def update_hopfield_network(state, weights, max_iter=100):
    for _ in range(max_iter):
        new_state = np.sign(np.dot(weights, state))
        if np.array_equal(new_state, state):
            return new_state
        state = new_state
    return state

# Test the network
if __name__ == "__main__":
    patterns = [[1, 1, -1, -1],
                [-1, -1, 1, 1],
                [1, -1, 1, -1],
                [-1, 1, -1, 1]]

    weights = train_hopfield_network(patterns)

    # Add a noisy pattern
    noisy_pattern = [1, 1, 1, 1]

    print("Noisy Pattern:", noisy_pattern)

    recalled_state = update_hopfield_network(noisy_pattern, weights)
    print("Recalled Pattern:", recalled_state)
    print("Energy:", energy(recalled_state, weights))


Noisy Pattern: [1, 1, 1, 1]
Recalled Pattern: [1. 1. 1. 1.]
Energy: 8.0
