In [46]:
import numpy as np

In [47]:
def train(inputs,b,t,rho,l,n):
    print("Initial weigths of b: \n",b)
    print("Initial weigths of t: \n",t)
    
    for s in inputs:
        norm_s=np.sum(s)
        print("Norm of ||s||:",norm_s,"\n")
        
        x=s
        y=np.dot(x,b)
        print("\ny=bij*x:",y)
        J=winner(y)
        print("\nWinner J=",J)
        
        xi=s*t[J]
        norm_xi=np.sum(xi)
        print("\nNorm of x:",norm_xi)
        
        test=norm_xi/norm_s
        
        if test>=rho:
            print('reset false')
            for i in range(n):
                b[i][J]=(l*xi[i])/((l-1)+norm_xi)
                t[J][i]=xi[i]
            print("\nbij new:",b)
            print("\ntji new:",t)
        else :
            print('reset true')
def winner(y):
    j=0
    for i in range(len(y)):
        if(y[i]>y[j]):
            j=i
    return j

import numpy as np

inputs = np.array([[1,1,0,0], [0, 0, 0, 1], [1, 0, 0, 0], [0, 0, 1, 1]])
rho = 0.4
learning_rate = 2
n = 4
m = 3
norm_s = 1
norm_x = 1
bottom = 1/(1+n)

b=np.full((n,m),bottom)
t=np.full((m,n),1)

train(inputs,b,t,rho,learning_rate,n)

In [48]:
import numpy as np

inputs = np.array([[1,1,0,0], [0, 0, 0, 1], [1, 0, 0, 0], [0, 0, 1, 1]])
rho = 0.4
learning_rate = 2
n = 4
m = 3
norm_s = 1
norm_x = 1
bottom = 1/(1+n)

In [49]:
b=np.full((n,m),bottom)
t=np.full((m,n),1)

In [50]:
train(inputs,b,t,rho,learning_rate,n)

Initial weigths of b: 
 [[0.2 0.2 0.2]
 [0.2 0.2 0.2]
 [0.2 0.2 0.2]
 [0.2 0.2 0.2]]
Initial weigths of t: 
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
Norm of ||s||: 2 


y=bij*x: [0.4 0.4 0.4]

Winner J= 0

Norm of x: 2
reset false

bij new: [[0.66666667 0.2        0.2       ]
 [0.66666667 0.2        0.2       ]
 [0.         0.2        0.2       ]
 [0.         0.2        0.2       ]]

tji new: [[1 1 0 0]
 [1 1 1 1]
 [1 1 1 1]]
Norm of ||s||: 1 


y=bij*x: [0.  0.2 0.2]

Winner J= 1

Norm of x: 1
reset false

bij new: [[0.66666667 0.         0.2       ]
 [0.66666667 0.         0.2       ]
 [0.         0.         0.2       ]
 [0.         1.         0.2       ]]

tji new: [[1 1 0 0]
 [0 0 0 1]
 [1 1 1 1]]
Norm of ||s||: 1 


y=bij*x: [0.66666667 0.         0.2       ]

Winner J= 0

Norm of x: 1
reset false

bij new: [[1.  0.  0.2]
 [0.  0.  0.2]
 [0.  0.  0.2]
 [0.  1.  0.2]]

tji new: [[1 0 0 0]
 [0 0 0 1]
 [1 1 1 1]]
Norm of ||s||: 2 


y=bij*x: [0.  1.  0.4]

Winner J= 1

Norm of x: 1
reset f