In [1]:
import numpy as np


In [2]:
np.random.seed(2)

In [3]:
x=np.array([[0,0],[1,1],[1,0],[0,1]])
y=np.array([[0],[0],[1],[1]])

In [4]:
# x=x/np.amax(x,axis=0)
# y=y/100

In [5]:
x,y

(array([[0, 0],
        [1, 1],
        [1, 0],
        [0, 1]]),
 array([[0],
        [0],
        [1],
        [1]]))

In [6]:
class NeuralNetwork():
    def __init__(self,inp_size,hidden_size,output_size):
        self.inp_size=inp_size
        self.output_size=output_size
        self.hidden_size=hidden_size 
#         self.bias1=np.random.uniform(-0.1,0.1,(1,self.hidden_size))
#         self.bias2=np.random.uniform(-0.1,0.1,(1,self.output_size))
        self.bias1=0
        self.bias2=0
        self.w1=np.random.uniform(-0.1,0.5,(self.inp_size,self.hidden_size))
        self.w2=np.random.uniform(-0.1,0.5,(self.hidden_size,self.output_size))
    
    def sigmoid(self,x):
        return 1/(1+np.exp(-x))
    
    def sigmoid_derivative(self,s):
        return s*(1-s)
    
    def feedforward(self,x):
        self.summation=np.dot(x,self.w1)+self.bias1
        self.hidden_layer_inp=self.sigmoid(self.summation)
        
        self.hidden_sum=np.dot(self.hidden_layer_inp,self.w2)+self.bias2
        output=self.sigmoid(self.hidden_sum)
        return output
    
    def backpropagation(self,x,y,output,lr):
        
#         self.error = y - output
#         self.output_delta = self.error * self.sigmoid_derivative(output)

#         self.hidden_error = np.dot(self.output_delta, self.w2.T)  # Calculate error in the hidden layer
#         self.hidden_delta = self.hidden_error * self.sigmoid_derivative(self.hidden_layer_inp)

#         self.w1 += np.dot(x.T, self.hidden_delta) * lr
#         self.w2 += np.dot(self.hidden_layer_inp.T, self.output_delta) * lr

#         self.bias1 += np.sum(self.hidden_delta, axis=0) * lr
#         self.bias2 += np.sum(self.output_delta, axis=0) * lr
        self.error=y-output
        self.output_delta=self.error*self.sigmoid_derivative(output)
        
        self.hidden_error=self.output_delta.dot(self.w2.T)
        self.hidden_delta=self.hidden_error*self.sigmoid_derivative(self.hidden_layer_inp)
        
        self.w1+=x.T.dot(self.hidden_delta)*lr
        self.w2+=self.hidden_layer_inp.T.dot(self.output_delta)*lr
        
        self.bias1+=np.sum(self.hidden_delta)*lr
        self.bias2+=np.sum(self.output_delta)*lr
        
    def train(self,x,y,epochs):
        for epoch in range(epochs):
            output=self.feedforward(x)
            self.backpropagation(x,y,output,0.1)
            if epoch%250==0:
                print('loss: ',np.mean(np.square(y-output)))

In [7]:
inp_size=x.shape[1]
op_size=y.shape[1]
hidden_size=4
NN=NeuralNetwork(inp_size,hidden_size,op_size)
x.shape[1],y.shape[1]

(2, 1)

In [10]:
NN.train(x,y,100000)

loss:  0.2018392955322427
loss:  0.1824048241158069
loss:  0.1565308786774565
loss:  0.12263129825771073
loss:  0.08663071966576769
loss:  0.05870894096535755
loss:  0.04083391426537325
loss:  0.029787224579726962
loss:  0.022737327421045263
loss:  0.018023948870647618
loss:  0.014729354083107474
loss:  0.012335449511195924
loss:  0.010537845634448463
loss:  0.009150027315600759
loss:  0.008053121907965276
loss:  0.007168640717929853
loss:  0.0064431100761661855
loss:  0.005839077525052709
loss:  0.005329663531874453
loss:  0.0048951552871605
loss:  0.004520815542740329
loss:  0.004195436277631637
loss:  0.00391036153013172
loss:  0.003658813159687327
loss:  0.003435416659150474
loss:  0.0032358618186332363
loss:  0.003056656013108076
loss:  0.0028949422121324515
loss:  0.0027483629344541402
loss:  0.0026149572952583423
loss:  0.0024930822107913455
loss:  0.002381351457872255
loss:  0.002278588082846232
loss:  0.002183786898799042
loss:  0.0020960846829321316
loss:  0.00201473630628668

loss:  0.0001638321530744272
loss:  0.00016319077055432414
loss:  0.00016255425271762775
loss:  0.00016192254510579384
loss:  0.00016129559406421697
loss:  0.00016067334672752957
loss:  0.00016005575100521622
loss:  0.00015944275556753194
loss:  0.00015883430983173536
loss:  0.00015823036394861547
loss:  0.00015763086878931037
loss:  0.00015703577593240327
loss:  0.0001564450376512949
loss:  0.00015585860690184989
loss:  0.00015527643731029104
loss:  0.00015469848316137456
loss:  0.00015412469938678265
loss:  0.00015355504155379173
loss:  0.00015298946585414288
loss:  0.00015242792909318025
loss:  0.00015187038867918703
loss:  0.00015131680261295198
loss:  0.00015076712947755607
loss:  0.00015022132842836423
loss:  0.00014967935918321925
loss:  0.00014914118201283852
loss:  0.00014860675773140797
loss:  0.0001480760476873675
loss:  0.00014754901375437564
loss:  0.00014702561832246241
loss:  0.00014650582428936434
loss:  0.00014598959505201424
loss:  0.00014547689449822794
loss:  0.0001

In [11]:
print(NN.feedforward(x))

[[0.01298305]
 [0.00907902]
 [0.99012124]
 [0.99012137]]
